"""Per-error-type analysis of trained FLAN-T5-Large on BEA 2019 test set.

Runs after evaluate_bea2019.py has generated predictions.
Uses ERRANT to categorize errors and compute per-type metrics.
"""

import time
import pandas as pd
from tqdm import tqdm

from src.training.evaluate import per_error_analysis


def main():
    print("=" * 70)
    print("PER-ERROR-TYPE ANALYSIS - FLAN-T5-LARGE (BEA 2019)")
    print("=" * 70)

    # Load predictions (generated by evaluate_bea2019.py)
    pred_path = "checkpoints/flan_t5_large_bea2019/evaluation_predictions.csv"
    print(f"\nLoading predictions from: {pred_path}")
    df = pd.read_csv(pred_path)
    df = df.dropna()
    print(f"  Samples: {len(df)}")

    sources = df["source"].tolist()
    predictions = df["prediction"].tolist()
    references = df["reference"].tolist()

    # Run per-error-type analysis (uses ERRANT, may be slow)
    print("\nRunning per-error-type analysis with ERRANT...")
    print("  (This parses every sentence with spaCy - may take 15-30 minutes)")
    start = time.time()
    results = per_error_analysis(
        predictions=predictions,
        sources=sources,
        references=references,
    )
    elapsed = time.time() - start
    print(f"  Analysis completed in {elapsed:.1f}s")

    # Display results sorted by total reference count (most common errors first)
    print("\n" + "=" * 70)
    print("PER-ERROR-TYPE RESULTS (sorted by frequency)")
    print("=" * 70)
    print(f"{'Error Type':<25} {'Total':>6} {'TP':>5} {'FP':>5} {'FN':>5} {'Prec':>7} {'Rec':>7} {'F0.5':>7}")
    print("-" * 70)

    sorted_types = sorted(
        results.items(), key=lambda x: x[1]["total_ref"], reverse=True
    )

    for error_type, metrics in sorted_types:
        print(
            f"{error_type:<25} {metrics['total_ref']:>6.0f} "
            f"{metrics['tp']:>5.0f} {metrics['fp']:>5.0f} {metrics['fn']:>5.0f} "
            f"{metrics['precision']:>7.4f} {metrics['recall']:>7.4f} {metrics['f05']:>7.4f}"
        )

    # Aggregate by coarse categories
    print("\n" + "=" * 70)
    print("COARSE CATEGORY SUMMARY")
    print("=" * 70)
    coarse = {}
    for error_type, metrics in results.items():
        # ERRANT format: {M|R|U}:{TYPE} - extract the main category
        parts = error_type.split(":")
        if len(parts) >= 2:
            category = parts[1]  # e.g., VERB, DET, PREP, NOUN, etc.
        else:
            category = error_type

        if category not in coarse:
            coarse[category] = {"tp": 0, "fp": 0, "fn": 0}
        coarse[category]["tp"] += int(metrics["tp"])
        coarse[category]["fp"] += int(metrics["fp"])
        coarse[category]["fn"] += int(metrics["fn"])

    print(f"{'Category':<20} {'Total':>6} {'TP':>5} {'FP':>5} {'FN':>5} {'Prec':>7} {'Rec':>7} {'F0.5':>7}")
    print("-" * 70)

    sorted_coarse = sorted(
        coarse.items(), key=lambda x: x[1]["tp"] + x[1]["fn"], reverse=True
    )

    for category, counts in sorted_coarse:
        tp, fp, fn = counts["tp"], counts["fp"], counts["fn"]
        total = tp + fn
        p = tp / (tp + fp) if (tp + fp) > 0 else 0
        r = tp / (tp + fn) if (tp + fn) > 0 else 0
        f05 = 1.25 * p * r / (0.25 * p + r) if (p + r) > 0 else 0
        print(f"{category:<20} {total:>6} {tp:>5} {fp:>5} {fn:>5} {p:>7.4f} {r:>7.4f} {f05:>7.4f}")

    # Save results
    output_path = "checkpoints/flan_t5_large_bea2019/error_type_analysis.txt"
    with open(output_path, "w") as f:
        f.write("PER-ERROR-TYPE ANALYSIS - FLAN-T5-Large + LoRA (BEA 2019)\n")
        f.write("=" * 70 + "\n\n")
        f.write(f"{'Error Type':<25} {'Total':>6} {'TP':>5} {'FP':>5} {'FN':>5} {'Prec':>7} {'Rec':>7} {'F0.5':>7}\n")
        f.write("-" * 70 + "\n")
        for error_type, metrics in sorted_types:
            f.write(
                f"{error_type:<25} {metrics['total_ref']:>6.0f} "
                f"{metrics['tp']:>5.0f} {metrics['fp']:>5.0f} {metrics['fn']:>5.0f} "
                f"{metrics['precision']:>7.4f} {metrics['recall']:>7.4f} {metrics['f05']:>7.4f}\n"
            )
    print(f"\nResults saved to: {output_path}")


if __name__ == "__main__":
    main()
